# Generated by Django 5.1.2 on 2024-11-02 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_repomodel_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repomodel',
            name='path',
        ),
    ]
