# Generated by Django 5.1.2 on 2024-11-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_remove_repomodel_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='repomodel',
            name='description',
            field=models.CharField(default='Hola mundo', max_length=600),
            preserve_default=False,
        ),
    ]
