# Generated by Django 5.1.2 on 2024-11-10 00:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_repomodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='repomodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
